cms/cms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customers/', include('customers.urls')),
    path('', RedirectView.as_view(url='customers/')),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

cms/customers/urls.py
from django.conf.urls import handler403, handler404, handler500
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = "customers"
urlpatterns = [

	path(
		'change-password/', 
		auth_views.PasswordChangeView.as_view(
			template_name="user/change_password.html", 
			success_url="/"), 
		name='change-password'),

	path('', views.CustomerListView.as_view(), name="customer-list"),
	path('<int:pk>/', views.CustomerDetialView.as_view(), name="customer-detail"),

	path('create/', views.CustomerCreate.as_view(), name='customer-create'),
	path('<int:pk>/update/', views.CustomerUpdate.as_view(), name='customer-update'),
	path('<int:pk>/delete/', views.CustomerDelete.as_view(), name='customer-delete'),
    path('delete-all/', views.delete_all_customers, name="delete-all"),

	# path('import-csv/', views.import_as_csv, name="import-csv"),
	path('export-csv/', views.export_as_csv, name="export-csv"),
    path('export-pdf/', views.export_as_pdf , name="export-pdf"),
]

handler403 = views.error_403
handler404 = views.error_404
handler500 = views.error_500

cms/customers/models.py
from django.db import models
from django.urls import reverse

class Customer(models.Model):
	name = models.CharField(max_length=200)
	account = models.CharField(max_length=200)
	information = models.TextField(null=True, blank=True)
	remarks = models.TextField(null=True, blank=True)
	info_created_at = models.DateTimeField(auto_now_add=True)
	info_updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('customers:customer-detail', args=[str(self.id)])

	class Meta:
		permissions = (('can_manage_customers', 'Customer CRUD Operations'),)

cms/customers/forms.py
import csv
from django import forms
from django.core.exceptions import ValidationError


class CSVUploadFileForm(forms.Form):
	csv_file = forms.FileField(label="Select a CSV file with valid format to import data.", widget=forms.FileInput(attrs={'accept':'.csv', 'class': 'form-control'}))

cms/customers/views.py
import csv
import io
from weasyprint import HTML
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from customers.forms import CSVUploadFileForm
from customers.models import Customer


class CustomerListView(LoginRequiredMixin, generic.ListView):
	model = Customer


class CustomerDetialView(LoginRequiredMixin, generic.DetailView):
	model = Customer


class CustomerCreate(PermissionRequiredMixin, CreateView):
	permission_required = 'customers.can_manage_customers'
	model = Customer
	fields = '__all__'


class CustomerUpdate(PermissionRequiredMixin, UpdateView):
	permission_required = 'customers.can_manage_customers'
	model = Customer
	fields = ['name', 'account', 'information', 'remarks']


class CustomerDelete(PermissionRequiredMixin, DeleteView):
	permission_required = 'customers.can_manage_customers'
	model = Customer
	success_url = reverse_lazy('customers:customer-list')


@permission_required('customers.can_manage_customers')
def delete_all_customers(request):
	Customer.objects.all().delete()
	return redirect(reverse('customers:customer-list'))


@login_required
def import_as_csv(request):
	if request.method == 'POST':
		form = CSVUploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			#handle_csv_import(request.FILES['csv_file'])
			# return redirect(reverse('customers:customer-list'))
			return HttpResponse(handle_csv_import(request.FILES['csv_file']))
	else:
		form = CSVUploadFileForm()
	return render(request, 'customers/csv_upload_form.html', {'form': form})


def handle_csv_import(csv_file):
	csv_file.seek(0)  # go to starting point
	rows = csv.DictReader(io.StringIO(csv_file.read().decode('utf-8')))
	for row in rows:
		row = ', '.join(row)
		# customer = Customer.objects.create(name=row[1], account=row[2], information=row[3], remarks=row[4])
		# customer.save()



@login_required
def export_as_csv(request):
	customers = Customer.objects.order_by('name')
	if customers.count() == 0:
		return redirect(reverse('customers:customer-list'))

	response_data = HttpResponse(content_type='text/csv')
	response_data['Content-Disposition'] = 'attachment; filename="customer_list.csv"'
	# csv_headers = ['Name', 'Account', 'Information', 'Remarks']
	writer = csv.writer(response_data)
	# writer.writerow(csv_headers)
	for customer in customers:
		csv_data = [customer.name, customer.account, customer.information, customer.remarks]
		writer.writerow(csv_data)
	return response_data


@login_required
def export_as_pdf(request):
	customers = Customer.objects.order_by('name')
	if customers.count() == 0:
		return redirect(reverse('customers:customer-list'))
	# return render(request, 'customers/pdf.html', {'customers': customers})
	html_string = render_to_string('customers/pdf.html', {'customers': customers})
	html = HTML(string=html_string)
	html.write_pdf(target='tmp_storage/customer_list.pdf')
	fss = FileSystemStorage('tmp_storage/')
	with fss.open('customer_list.pdf') as pdf:
		response_data = HttpResponse(pdf, content_type="application/pdf")
		response_data['Content-Disposition'] = 'attachment; filename="customer_list.pdf"'
	return response_data


""" Error pages """

def error_403(request, exception):
	return render(request, '403.html', {})


def error_404(request, exception):
	return render(request, '404.html', {})


def error_500(request):
	return render(request, '500.html', {})

cms/customers/templates/customers/base_generic.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>CMS | {% block title %}{% endblock title %}</title>
	{% load static %}
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-materia.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome5.13/css/all.css' %}">
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12 branding">
				{% if user.is_authenticated %}
				<div class="text-right">
					<div class="dropdown">
						<a class="dropdown-toggle" href="#" role="button" id="userdropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<b>Welcome:</b> {{ user.username }}
						</a>
					  
						<div class="dropdown-menu" aria-labelledby="userdropdown">
							<p class="dropdown-item"><i class="fa fa-calendar" aria-hidden="true"></i> Last Login: {{ user.last_login }}</p>
							<div class="dropdown-divider"></div>
							<a href="{% url 'customers:change-password' %}" class="dropdown-item"><i class="fa fa-key" aria-hidden="true"></i> Change Password</a>
							<a href="{% url 'logout' %}?next={{ request.path }}" class="dropdown-item"><i class="fa fa-sign-out-alt" aria-hidden="true"></i> Logout</a>
						</div>
					  </div>
				</div>
				{% endif %}
				<h1><a href="{% url 'customers:customer-list' %}">Welcome to Customer Management System!</a></h1>
			</div>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div id="sidebar" class="col-md-2 sidebar">
				<a href="{% url 'customers:customer-list' %}" class="btn btn-primary btn-block"><i class="fa fa-home"></i> Home</a>
				{% if perms.customers.can_manage_customers %}
					<a id="add-new-customer" href="{% url 'customers:customer-create' %}" class="btn btn-warning btn-block">
						<i class="fa fa-plus"></i> Add New Customer
					</a>
					<!-- <a href="#" class="btn btn-outline-success btn-block">
						<i class="fa fa-file-csv"></i> Import CSV
					</a> -->
				{% endif %}
				{% if customer_list.count >= 1 %}
					<a href="{% url 'customers:export-csv' %}" class="btn btn-outline-success btn-block">
						<i class="fa fa-file-csv"></i> Export as CSV
					</a>
					<a href="{% url 'customers:export-pdf' %}" class="btn btn-outline-success btn-block"><i class="fa fa-file-pdf"></i> Export as PDF</a>
				{% endif %}

			{% block sidebar %}
			{% endblock sidebar %}
			</div>
			<div class="col-md-10 content">
				{% block content %}
				{% endblock content %}
			</div>
		</div>
	</div>
	<div class="container-fluid footer">
		<div class="row">
			<div class="col-md-12">
				<p class="text-center developer">Developed by: <span class="developer-name">Chit Ko Ko Oo</span></p>
			</div>
		</div>
	</div>
</body>
</html>

<script src="{% static 'js/jquery-3.5.1.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'fontawesome5.13/js/all.js' %}"></script>
{% block javascript %}
{% endblock javascript %}

cms/customers/templates/customers/csv_upload_form.html
{% extends 'customers/base_generic.html' %}

{% block title %} Import CSV {% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
	<h3></h3>
	<form enctype="multipart/form-data" method="POST" class="form">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit" name="customer-csv-import" class="btn btn-primary">
            <i class="fa fa-check"></i> Import CSV
        </button>
	</form>

{% endblock content %}

cms/customers/templates/customers/customer_confirm_delete.html
{% extends "customers/base_generic.html" %}

{% block title %}
	Delete Customer Confirmation: {{ customer.name }}
{% endblock title %}

{% block content %}
	<h2>Delete Customer</h2>
	<hr>
	<p>Are you sure you want to delete the customer: <b> {{ customer }}?</p>	

	<form action="" method="POST">
		{% csrf_token %}
		<button type="submit" name="customer-delete-confirmation" class="btn btn-danger">
            <i class="fa fa-trash"></i> Yes, Delete!
        </button>
		<a href="{% url 'customers:customer-list' %}" class="btn btn-outline-secondary"><i class="fa fa-times"></i> Cancel</a>
	</form>

{% endblock content %}

cms/customers/templates/customers/customer_detail.html
{% extends "customers/base_generic.html" %}
{% block title %} Customer: {{ customer.name }} {% endblock %}

{% block content %}
<a href="{% url 'customers:customer-list' %}" class="btn btn-outline-primary"><i class="fa fa-arrow-left"></i> Back to customer list</a>
<br><br>
<h3><b>Customer Name:</b> {{ customer.name }}</h3>
<hr>
<div class="container detail-items">
	<div class="row">
		<div class="col-md-2"><b>Account Number:</b></div>
		<div class="col-md-10">{{ customer.account }}</div>
	</div>
	<div class="row">
		<div class="col-md-2"><b>Information:</b></div>
		<div class="col-md-10">{{ customer.information }}</div>
	</div>
	<div class="row">
		<div class="col-md-2"><b>Remarks:</b></div>
		<div class="col-md-10">{{ customer.remarks }}</div>
	</div>

	{% load tz %}
	
	<div class="row">
		<div class="col-md-2"><b>Info Created Time:</b></div>
		<div class="col-md-10">{{ customer.info_created_at|localtime }}</div>
	</div>
	<div class="row">
		<div class="col-md-2"><b>Info Updated Time:</b></div>
		<div class="col-md-10">{{ customer.info_updated_at|localtime }}</div>
	</div>

</div>
{% endblock content %}

cms/customers/templates/customers/customer_form.html
{% extends "customers/base_generic.html" %}

{% block title %}
	{% if customer %}
		Update Customer: {{ customer.name }}
	{% else %}
		Add New Customer
	{% endif %}
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
	<h3>
		{% if customer %}
			<b>Customer:</b> {{ customer.name }}
		{% else %}
			<b>New Customer</b>
		{% endif %}	
	</h3>
	<hr>
	<form action="" method="POST" class="form">
		{% csrf_token %}
		<div class="row">
			<div class="col-md-6">
				{{ form.name|as_crispy_field }}
			</div>
			<div class="col-md-6">
				{{ form.account|as_crispy_field }}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				{{ form.information|as_crispy_field }}
			</div>
			<div class="col-md-6">
				{{ form.remarks|as_crispy_field}}
			</div>
		</div>
		{% if customer %}
		<button type="submit" name="update-customer" class="btn btn-lg btn-warning">
			<i class="fa fa-check"></i> Update
		</button>
		{% else %}
		<button type="submit" name="new-customer" class="btn btn-lg btn-warning">
			<i class="fa fa-check"></i> Add
		</button>
		{% endif %}
		<a href="{% url 'customers:customer-list' %}" class="btn btn-lg btn-outline-secondary">
			<i class="fa fa-times"></i> Cancel
		</a>
	</form>
{% endblock content %}

cms/customers/templates/customers/customer_list.html
{% extends "customers/base_generic.html" %}

{% block title %} Customer List {% endblock title %}

{% block content %}
	{% if customer_list %}
	<p>There {{customer_list.count|pluralize:"is,are"}} totally <b> {{ customer_list.count }} </b>customer{{customer_list.count|pluralize }}.</p>
	
	<input type="text" id="search-name" onkeyup="searchName()" placeholder="Search by name">
	</input>

	
	{% if perms.customers.can_manage_customers %}
	<div class="text-right text-danger">
		<button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#deleteAllModal">Delete All</button>
	</div>
	
	<!-- Modal -->
	<div class="modal fade" id="deleteAllModal" tabindex="-1" role="dialog" aria-labelledby="deleteAllModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="deleteAllModalLabel">Confirmation!</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        <p class="text-danger">Are you sure you want to delete all customers? This cannot be undone.</p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> Cancel</button>
	        <a href="{% url 'customers:delete-all' %}" class="btn btn-danger"><i class="fa fa-trash"></i> Yes, Delete All Customers!</a>
	      </div>
	    </div>
	  </div>
	</div>
	{% endif %}  <!-- end of delete all customer permission -->


	<table id="customer-table" class="table table-hover">
		<thead id="customer-table-header" class="thead-dark">
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Account</th>
				<th>Information</th>
				<th>Remarks</th>
				<!--<th>Info Created</th>
				<th>Info Updated</th> -->
				<th>View</th>
				{% if perms.customers.can_manage_customers %}
				<th>Edit</th>
				<th>Delete</th>
				{% endif %}
			</tr>
		</thead>
		<tbody>
			{% for customer in customer_list %}
				<tr>
					<th>{{ forloop.counter }}</th>
					<td>{{ customer.name }}</td>
					<td>{{ customer.account }}</td>
					<td>{{ customer.information }}</td>
					<td>{{ customer.remarks }}</td>
					<!-- <td><span class="badge">{{ customer.info_created_at }}</span></td>
					<td><span class="badge">{{ customer.info_updated_at }}</span></td> -->
					<td>
						<a href="{% url 'customers:customer-detail' customer.id %}" class="btn btn-sm btn-outline-primary"><i class="fa fa-eye"></i> View</a>
					</td>
					{% if perms.customers.can_manage_customers %}
					<td>
						<a href="{% url 'customers:customer-update' customer.id %}" class="btn btn-sm btn-outline-warning"><i class="fa fa-0.5x fa-edit"></i> Edit</a>
					</td>
					<td>
						<a href="{% url 'customers:customer-delete' customer.id %}" class="btn btn-sm btn-outline-danger"><i class="fa fa-trash"></i> Delete</a>
					</td>
					{% endif %}
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
		<p class="text-danger">There is no customer right now.</p>
	{% endif %}

<button id="goToTopButton" onclick="topFunction();">Top</button>

{% endblock content %}

{% block javascript %}
<script>
	function searchName() {
		var input, filter, table, tr, td, i, txtValue;
		input = document.getElementById("search-name");
		filter = input.value.toUpperCase();
		table = document.getElementById("customer-table");
		tr = table.getElementsByTagName("tr");

		for (i = 0; i < tr.length; i++){
			td = tr[i].getElementsByTagName('td')[0];
			if (td) {
				txtValue = td.textContent || td.innerText;
				if (txtValue.toUpperCase().indexOf(filter) > -1) {
					tr[i].style.display = "";
				} else {
					tr[i].style.display = "none";
				}
			}
		}
	}

	// Go to top
	mybutton = document.getElementById("goToTopButton");
	window.onscroll = function() {
		if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
			mybutton.style.display = "block";
		} else {
			mybutton.style.display = "none";
		}
	}
	function topFunction() {
		document.body.scrollTop = 0;  // for safari
		document.documentElement.scrollTop = 0;  // for chrome, firefox, ie and opera
	}

</script>
{% endblock javascript %}

cms/customers/templates/user/change_password.html
{% extends 'customers/base_generic.html' %}


{% block title %}
    Change Password
{% endblock title %}
    

{% block content %}
{% load crispy_forms_tags %}

<h3>Change Password</h3>
<hr>
<form method="POST" class="form">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Change Password</button>
    <a href="{% url 'customers:customer-list' %}" class="btn btn-outline-secondary"><i class="fa fa-times" aria-hidden="true"></i> Cancel</a>
</form>

{% endblock content %}
    